module "infra-cloudflare" {
  source                         = "../../modules/infra-cloudflare"
  cloudflare_api_token           = var.cloudflare_api_token
  cloudflare_account_id          = var.cloudflare_account_id
  domain                         = var.domain
  environment                    = var.environment
  dns_records                    = var.dns_records
  edge_certificates              = var.edge_certificates
  waf_custom_rules               = var.waf_custom_rules
  waf_rate_limits                = var.waf_rate_limits
  waf_firewall_rules             = var.waf_firewall_rules
  tunnels                        = var.tunnels
  gcp_push_tunnel_tokens         = var.gcp_push_tunnel_tokens
  gcp_project_id                 = var.gcp_project_id
  gcp_tunnel_token_secret_prefix = var.gcp_tunnel_token_secret_prefix
  gcp_secret_labels              = var.gcp_secret_labels
  access_groups                  = var.access_groups
  access_applications            = var.access_applications
  access_policies                = var.access_policies
  github_client_id               = var.github_client_id
  github_client_secret           = var.github_client_secret
}
